version: '3'
services:
  backend:
    build:
      context: ../back-end
    ports:
      - '3001:3001'
    env_file:
      - ../.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
