version: '3'
services:
  backend:
    build: .
    ports:
      - '3001:3001'
    env_file:
      - ../.env
    networks:
      - app-network

  db:
    image: postgres
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ../.env
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
