name: Code Quality Check

on:
  push:
    branches:
      - '**'

jobs:
  lint-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('back-end/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./back-end

      - name: Run ESLint
        run: npm run lint
        working-directory: ./back-end

      - name: Run Prettier
        run: npm run prettier
        working-directory: ./back-end

      - name: Stop and remove Docker container
        run: docker stop kanban-back-test && docker rm kanban-back-test

  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('front-end/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./front-end

      - name: Run ESLint
        run: npm run lint
        working-directory: ./front-end

      - name: Run Prettier
        run: npm run prettier
        working-directory: ./front-end
